name: Adrian Sampson

markdown: redcarpet
redcarpet:
    extensions: [smart]

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json

navigation:
    - title: home
      link: /
    - title: contact
      link: /contact.html
    - title: blog
      link: /blog/
    - title: research
      link: /research.html
    - title: '&amp;c.'
      link: /etc.html
