name: Adrian Sampson
author: Adrian Sampson
url: http://homes.cs.washington.edu/~asampson
base: ''
twitter: '@samps'
email: 'asampson@cornell.edu'

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    enable_coderay: false
    auto_ids: true
    entity_output: symbolic
highlighter: null

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - Makefile

permalink: /blog/:title.html

defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

navigation:
    - title: home
      link: /
    - title: research
      link: /research.html
    - title: blog
      link: /blog/
    - title: contact
      link: /contact.html
    - title: '&amp;c.'
      link: /misc.html
